name: surfna-infer
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - pyyaml
  - tqdm
  - scikit-learn
  - biopython
  - rdkit
  - mdanalysis
  - biopandas
  - loguru
  - joblib
  - networkx
  - pytorch
  - pytorch-cuda=11.8
  - pyg
  - pip:
      - accelerate
      - e3nn
      - fair-esm
      - meeko
      - plyfile
      - prefetch-generator
      - wandb
