adapter_rank: 8
adapter_scope: surface
all_atoms: false
atom_max_neighbors: 8
atom_radius: 5
atom_type_prediction: false
batch_size: 4
bond_type_prediction: false
c_alpha_max_neighbors: 24
cache_path: null
config: null
cross_distance_embed_dim: 32
cross_max_distance: 80
cudnn_benchmark: true
data_dir: null
distance_embed_dim: 32
dropout: 0.1
dynamic_max_cross: true
ema_rate: 0.999
embedding_scale: 1000
embedding_type: sinusoidal
esm_embeddings_path: null
freeze_backbone: false
gradient_accumulation_steps: 1
inference_earlystop_goal: max
inference_earlystop_metric: valinf_rmsds_lt2
inference_steps: 20
ligand_distance_prediction: false
limit_complexes: 0
lm_embedding_dim: 0
lm_embedding_type: auto
log_dir: null
lr: 0.0005
matching: true
matching_maxiter: 20
matching_popsize: 20
max_lig_size: null
max_radius: 5.0
max_surface_vertices: 1500
mdn_aux_loss_weight: 0.001
mdn_dist_threshold_test: 5.0
mdn_dist_threshold_train: 7.0
mdn_dropout: 0.1
mdn_early_stop_patience: 30
model_type: surface_score_model
model_version: version3
n_epochs: 1000
n_gaussians: 20
no_batch_norm: false
no_torsion: false
ns: 48
nucleic_feat_dim: 12
num_conformers: 1
num_conv_layers: 6
num_dataloader_workers: 1
num_inference_complexes: 132
num_workers: 2
nv: 10
per_complex_timeout_sec: 180
pin_memory: false
progressive_unfreeze: false
project: SurfNA_NA_SurfaceOnlyTransfer_LatestProtein_FixMesh1_ExpandedHighConf_NoESM
receptor_radius: 15.0
remove_hs: true
residue_type_prediction: false
restart_dir: null
restart_file: null
restart_key_filter: all
restart_lr: null
rot_sigma_max: 1.55
rot_sigma_min: 0.03
rot_weight: 0.33
run_name: na_surfaceonly_latestprotein_fixmesh1_expanded_highconf_noesm_4gpu_surfmax1500_bs4_lr5e-4_2026_05_24_00_33_03
scale_by_sigma: true
scheduler: plateau
scheduler_patience: 50
sigma_embed_dim: 32
skip_inference_freq: 0
split_test: null
split_train: null
split_val: null
surface_feature_dim: 4
surface_lr_ratio: 0.5
surface_path: null
test_sigma_intervals: false
topN: 1
tor_sigma_max: 3.14
tor_sigma_min: 0.0314
tor_weight: 0.33
tr_sigma_max: 5.0
tr_sigma_min: 0.1
tr_weight: 0.33
train_inference_freq: null
transformStyle: diffdock
unfreeze_layers: ''
unfreeze_schedule: null
use_adaptive_transfer: true
use_ema: false
use_nucleic_feat_fusion: true
use_second_order_repr: false
val_inference_freq: 20
w_decay: 0.01
wandb: false
wandb_dir: wandb
