adapter_rank: 8
adapter_scope: surface
all_atoms: false
atom_max_neighbors: 8
atom_radius: 5
atom_type_prediction: true
batch_size: 8
bond_type_prediction: true
c_alpha_max_neighbors: 24
cache_path: /public/home/luoyuxuan/SurfNA/data/cache/na_surface4_probe14_salt150_ctx30_fixmesh1_clean_no_leak_blacklist_v5_scratch_nucfeat12
config: null
cross_distance_embed_dim: 32
cross_max_distance: 80
cudnn_benchmark: true
data_dir: /public/home/luoyuxuan/SurfNA/data/raw/na
distance_embed_dim: 32
dropout: 0.1
dynamic_max_cross: true
ema_rate: 0.999
embedding_scale: 1000
embedding_type: sinusoidal
esm_embeddings_path: null
freeze_backbone: false
gradient_accumulation_steps: 8
inference_earlystop_goal: max
inference_earlystop_metric: valinf_rmsds_lt2
inference_steps: 20
ligand_distance_prediction: false
limit_complexes: 0
lm_embedding_dim: 0
lm_embedding_type: auto
log_dir: /public/home/luoyuxuan/SurfNA/runs/mdn_na_officiallike_transfer_noesm
lr: 0.0001
matching: true
matching_maxiter: 20
matching_popsize: 20
max_lig_size: null
max_radius: 5.0
max_surface_vertices: 1500
mdn_aux_loss_weight: 0.001
mdn_dist_threshold_test: 5.0
mdn_dist_threshold_train: 7.0
mdn_dropout: 0.1
mdn_early_stop_patience: 30
model_type: mdn_model
model_version: version6
n_epochs: 250
n_gaussians: 20
no_batch_norm: false
no_torsion: true
ns: 40
nucleic_feat_dim: 12
num_conformers: 1
num_conv_layers: 4
num_dataloader_workers: 1
num_inference_complexes: 500
num_workers: 1
nv: 10
per_complex_timeout_sec: 180
pin_memory: false
progressive_unfreeze: false
project: SurfNA_MDN_NA_OfficialLike_Transfer_NoESM
receptor_radius: 15.0
remove_hs: true
residue_type_prediction: false
restart_dir: null
restart_file: /public/home/luoyuxuan/SurfNA/runs/mdn_protein_officiallike_noesm/protein_mdn4_officiallike_noesm_robust_lr5e4_effbs64_fixmesh1_2026_05_21_21_32_352026-05-21_21-32-49/best_model.pt
restart_key_filter: all
restart_lr: null
rot_sigma_max: 1.0e-21
rot_sigma_min: 1.0e-18
rot_weight: 0.33
run_name: na_mdn4_officiallike_transfer_noesm_robust_lr1e4_effbs64_fixmesh1_2026_05_21_21_32_352026-05-22_01-16-15
scale_by_sigma: true
scheduler: plateau
scheduler_patience: 10
sigma_embed_dim: 32
skip_inference_freq: 0
split_test: /public/home/luoyuxuan/SurfNA/data/splits/na_clean_test_oldsurf_resolved_fixmesh1
split_train: /public/home/luoyuxuan/SurfNA/data/splits/na_clean_train_no_leak_blacklist_v5_fixmesh1_ddp8
split_val: /public/home/luoyuxuan/SurfNA/data/splits/na_clean_val_no_leak_blacklist_v5_fixmesh1_ddp8
surface_feature_dim: 4
surface_lr_ratio: 0.5
surface_path: /public/home/luoyuxuan/SurfNA/data/surfaces/na_4feat_8A_probe14_salt150_ctx30_fixmesh1
test_sigma_intervals: true
topN: 1
tor_sigma_max: 1.0e-23
tor_sigma_min: 1.0e-21
tor_weight: 0.33
tr_sigma_max: 1.0e-20
tr_sigma_min: 1.0e-18
tr_weight: 0.33
train_inference_freq: null
transformStyle: diffdock
unfreeze_layers: ''
unfreeze_schedule: null
use_adaptive_transfer: false
use_ema: false
use_nucleic_feat_fusion: false
use_second_order_repr: false
val_inference_freq: 5
w_decay: 0.0
wandb: false
wandb_dir: wandb
