#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

: "${DATA_CSV:?Set DATA_CSV to the CSV generated by scripts/prepare_inference_csv.py}"
: "${MODEL_DIR:?Set MODEL_DIR to the generator checkpoint directory}"
: "${CONFIDENCE_MODEL_DIR:?Set CONFIDENCE_MODEL_DIR to the MDN checkpoint directory}"
: "${OUT_DIR:?Set OUT_DIR to an output directory}"
: "${CKPT:=best_inference_epoch_model.pt}"
: "${CONFIDENCE_CKPT:=best_model.pt}"
: "${SAMPLES_PER_COMPLEX:=40}"
: "${SAVE_TOP_N:=40}"
: "${BATCH_SIZE:=40}"
: "${BATCH_SIZE_MOLECULE:=1}"
: "${INFERENCE_STEPS:=20}"
: "${LIGANDS_MAX_ATOMS:=120}"
: "${RANDOM_SEED:=20260525}"

export PYTHONPATH="$ROOT_DIR/src:${PYTHONPATH:-}"

accelerate launch --num_processes "${NUM_GPUS:-1}" "$ROOT_DIR/src/inference_accelerate.py" \
  --data_csv "$DATA_CSV" \
  --model_dir "$MODEL_DIR" \
  --ckpt "$CKPT" \
  --confidence_model_dir "$CONFIDENCE_MODEL_DIR" \
  --confidence_ckpt "$CONFIDENCE_CKPT" \
  --out_dir "$OUT_DIR" \
  --samples_per_complex "$SAMPLES_PER_COMPLEX" \
  --save_docking_result_number "$SAVE_TOP_N" \
  --batch_size "$BATCH_SIZE" \
  --batch_size_molecule "$BATCH_SIZE_MOLECULE" \
  --inference_steps "$INFERENCE_STEPS" \
  --ligandsMaxAtoms "$LIGANDS_MAX_ATOMS" \
  --random_seed "$RANDOM_SEED" \
  --save_docking_result
