#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

: "${PROTEIN_PATH:?Full receptor PDB path}"
: "${POCKET_PATH:?Pocket PDB generated by surface/generate_surfaces.py}"
: "${SURFACE_PLY:?Surface PLY generated by surface/generate_surfaces.py}"
: "${LIGAND_LIBRARY:?Ligand SDF/MOL2 file or a directory of ligands}"
: "${MODEL_DIR:?Generator checkpoint directory}"
: "${CONFIDENCE_MODEL_DIR:?MDN checkpoint directory}"
: "${OUT_DIR:?Output directory}"

mkdir -p "$OUT_DIR"
DATA_CSV="${DATA_CSV:-$OUT_DIR/surfna_virtual_screen.csv}"

python "$ROOT_DIR/scripts/prepare_inference_csv.py" \
  --protein_path "$PROTEIN_PATH" \
  --pocket_path "$POCKET_PATH" \
  --surface_ply "$SURFACE_PLY" \
  --ligand_library "$LIGAND_LIBRARY" \
  ${REF_LIGAND:+--ref_ligand "$REF_LIGAND"} \
  --out_csv "$DATA_CSV"

DATA_CSV="$DATA_CSV" "$ROOT_DIR/scripts/run_inference.sh"
